### ISSUE TITLE
Incorrect key length

### ISSUE THREAD

**Issue by 3203920546** [WolframAlph/dh#1]
When I use dh.New() to generate an object, the length of his public key sometimes appears singular, which may be one byte more or one byte less

**Comment by WolframAlph** [comment]
Hi @3203920546. Can you provide concrete example? What group are you using, etc. Length of public key - do you refer to BitLen?

**Comment by 3203920546** [comment]
Sorry, this is not the error caused by your package.
I replaced `fmt.Sprintf("%x", server.PublicKey)` with `serverPubkey := hex.EncodeToString(server.PublicKey.Bytes())`
to get the correct hex encoding.
Thanks for your prompt reply
